version: '3'
services:
    redis:
        image: redis:6-alpine3.15
        hostname: redis
        ports:
        - "6379:6379"
        volumes:
        - "./redis/data:/data"
    db:
        image: postgres:13-alpine
        hostname: postgresql
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGPASSWORD: postgres
            POSTGRES_DB: postgres
            TZ: "Asia/Tokyo"
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data/
            # - db_volume:/var/lib/postgresql
        # restart: always
    app:
        build: ./python
        container_name: python_container
        hostname: python
        tty: true
        ports:
            - "8000:8000"
        volumes:
            - ./python/app:/app/
        depends_on:
            - db
    nginx:
        build: ./nginx
        container_name: nginx_container_py_ver
        hostname: nginx
        environment:
            - TZ=Asia/Tokyo
        ports:
            - "80:80"
        depends_on:
            - frontend
    frontend:
        build: ./front_js
        container_name: front_js
        hostname: frontend
        volumes:
            - ./front_js/expense-tracker:/usr/src/app/expense-tracker
            - /app/node_modules
            - /app/.next
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3000:3000"

volumes:
    db_volume: