# Generated by Django 4.0.1 on 2022-01-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
