# Generated by Django 4.0.1 on 2022-01-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_api', '0002_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
